### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by zyrolasting** [MaiaVictor/PureState#11]
Hi @MaiaVictor, and thank you for such a clean model. Even with blind spots in dependency detection, this is way more fun and intuitive to use than alternatives even 3 years later.

Question: What's your license for this? I ported this library to Racket [here](https://github.com/zyrolasting/kinda-ferpy) and credited you and this project as a basis for the current implementation. I figured that much was okay since other people have already done the same. Just wanted to be extra sure.

**Comment by VictorTaelin** [comment]
MIT, it should be on the repository. Sorry about that.

**Comment by zyrolasting** [comment]
No worries, thanks for confirming
